apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  selector:
    matchLabels:
      app: database-postgres
  serviceName: database-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: database-postgres
    spec:
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
        - name: database-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-volume
              mountPath: /local/database
          resources:
            requests:
              memory: "32Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: database-configmap
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-secret
